repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/python-poetry/poetry
    rev: "1.3"
    hooks:
      - id: poetry-lock
        args: ["--check"]
  - repo: local
    hooks:
      - id: codespell
        name: codespell
        entry: poetry run codespell --write-changes --skip="./*"
        language: system
        pass_filenames: false
        always_run: true
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        require_serial: true
      - id: ruff
        name: ruff
        entry: poetry run ruff
        language: system
        types: [python]
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
