repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, master, --branch, main]
  - repo: https://github.com/python-poetry/poetry
    rev: "1.3"
    hooks:
      - id: poetry-lock
        args: ["--check"]
  - repo: local
    hooks:
      - id: codespell
        name: codespell
        entry: poetry run codespell --write-changes --skip="./*"
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff format
        name: ruff format
        entry: poetry run ruff format
        language: system
        types: [python]
      - id: ruff lint
        name: ruff lint
        entry: poetry run ruff
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
