coverage:
  status:
    project:
      default:
        # allow a 2% drop from the previous base commit coverage
        target: auto
        threshold: 2%
        # See status checks but prevent them from blocking
        informational: true
    patch:
      default:
        informational: true
