version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  file:
    class: "logging.handlers.RotatingFileHandler"
    formatter: "simple"
    filename: ".log"
    filters:
      - "logfilter"

filters:
  logfilter:
    (): filters.RedactingFilter
    patterns:
      - "filterthisstring"

root:
  level: "DEBUG"
  handlers:
    - "file"
